---
# tasks file for kafka
- name: create directory for kafka configs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ kafka_stack_config_path }}"

- name: copy monitoring required files
  ansible.builtin.copy:
    src: "files/manifests/"
    dest: "{{ kafka_stack_config_path }}"
    mode: 0644

- name: deploy kafka stack
  ansible.builtin.shell: "kubectl apply -k {{ kafka_stack_config_path }}/"

...