apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: kafka-ns
spec:
  selector:
    app: kafka-exporter-deployment
    exporter: kafka
  type: ClusterIP
  ports:
  - port: 9308
    targetPort: 9308

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter-deployment
  namespace: kafka-ns
spec:
  selector:
    matchLabels:
      app: kafka-exporter-deployment
  template:
    metadata:
      name: kafka-exporter-pod
      namespace: kafka-ns
      labels:
        app: kafka-exporter-deployment
        exporter: kafka
    spec:
      containers:
      - name: kafka-exporter
        image: dockerhub.ir/bitnami/kafka-exporter:1.4.2
        imagePullPolicy: IfNotPresent
        args:
          - "--kafka.server=kafka-service:9092"
          - "--zookeeper.server=zookeeper-svc:2181"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9308
