---
# tasks file for rest_iptables

- name: "setup iptables in server"
  become: true
  tags:
    - iptables_role
  block:
    - name: "allow ip forwarding in kernel"
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
      when: "inventory_hostname in groups['loadbalancers']"

    - name: "copy rules for gateway hosts"
      ansible.builtin.template:
        src: "gw.v4.j2"
        dest: "/etc/iptables/rules.v4"
        mode: 0600
      when: "inventory_hostname in groups['loadbalancers']"

    - name: "copy rules for kuber nodes"
      ansible.builtin.template:
        src: "rules.v4.j2"
        dest: "/etc/iptables/rules.v4"
        mode: 0600
        trim_blocks: true
        lstrip_blocks: true
      when: "inventory_hostname in groups['kuber_nodes']"

    - name: "copy rules for edge servers"
      ansible.builtin.template:
        src: "edge.v4.j2"
        dest: "/etc/iptables/rules.v4"
        mode: 0600
        trim_blocks: true
        lstrip_blocks: true
      when: "inventory_hostname in groups['edges']"

    - name: "restart iptables-persistent"
      ansible.builtin.systemd:
        name: netfilter-persistent
        state: restarted
        enabled: true

    - name: "restart docker service"
      ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: true

...