{
 "title": "Kafka Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Topics",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (topic,job) (kafka_topic_partitions)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Number Of topics",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(kafka_topic_partitions{job=~\"Kafka\"}))"
    }
   ]
  },
  {
   "title": "Kafka Nodes",
   "type": "stat",
   "description": "Number of Kafka brokers",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_brokers{job=\"Kafka\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"Kafka\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(process_virtual_memory_bytes{job=~\"Kafka\"})",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}