{
 "title": "Zookeeper Overview",
 "description": "Zookeeper resource usage and throughput",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Alive Connections",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "num_alive_connections{job=\"zookeeper\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Open file descriptor Counter",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "open_file_descriptor_count{job=\"zookeeper\"}"
    }
   ]
  },
  {
   "title": "JVM Current Threads",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"zookeeper\"}"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance)(max_latency{job=\"zookeeper\"})"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance)(avg_latency{job=\"zookeeper\"})"
    }
   ]
  },
  {
   "title": "Max Client Response Size",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_client_response_size{job=\"zookeeper\"}"
    }
   ]
  },
  {
   "title": "Read Per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "read_per_namespace_count{job=\"zookeeper\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 7 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"zookeeper\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write Per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "write_per_namespace_count{job=\"zookeeper\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Response Packet Cache hit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "rate(response_packet_cache_hits{job=\"zookeeper\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"zookeeper\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"zookeeper\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connection Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "rate(connection_request_count{job=\"zookeeper\"}[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "JVM Thread State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "jvm_threads_state{job=\"zookeeper\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Min & Max Client Response Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "min_client_response_size{job=\"zookeeper\"}",
     "legendFormat": "minimum"
    },
    {
     "expr": "max_client_response_size{job=\"zookeeper\"}",
     "legendFormat": "Maximum"
    }
   ]
  }
 ]
}