---

- name: adding docker official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: add docker apt mirror
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
    https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: true

- name: install docker
  ansible.builtin.apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Install docker package
  ansible.builtin.pip:
    name: docker
    executable: pip3
    extra_args: "-i http://p.docker-registry.ir/PyPi/simple --trusted-host p.docker-registry.ir"

- name: add docker daemon.json file
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'

- name: create directory for docker.service.d
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755
    owner: root
    group: root

- name: enable and restart docker service
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: yes
...