---
# tasks file for kubectl-config
- name: Create .kube directory
  ansible.builtin.file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copy admin.conf to user's kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes

- name: create kubectl bash completion file
  shell: "kubectl completion bash > ~/.kube_complete"
  args:
    chdir: $HOME
    creates: .kube_complete

- name: add source command to bashrc file
  ansible.builtin.lineinfile:
    dest: $HOME/.bashrc
    insertafter: EOF
    line: "source $HOME/.kube_complete"
    backup: true

- name: re-read bashrc file
  ansible.builtin.shell: "/bin/bash -c 'source .bashrc'"
  args:
    chdir: $HOME
...