---
- name: get worker join token from master1 as a fact
  hosts: master1
  become: true
  gather_facts: true
  tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_worker_command_raw

    - name: Set join command
      set_fact:
        join_worker_command: "{{ join_worker_command_raw.stdout_lines[0] }}"

- name: join worker nodes with token
  hosts: workers
  become: true
  gather_facts: true
  tasks:
    - name: Remove debug file
      ansible.builtin.file:
        path: $HOME/worker_joined.txt
        state: absent

    - name: Join cluster
      ansible.builtin.shell: "{{ hostvars['master1'].join_worker_command }} >> worker_joined.txt"
      args:
        chdir: $HOME
        creates: joined.txt
      register: node
...