---
- name: setup private network
  hosts: all
  become: true
  gather_facts: false
  tags: apply_netplan
  roles:
    - role: "../roles/network/netplan"
      vars:
        eth1_ip: "{{ hostvars[inventory_hostname]['private_ip'] }}"
        eth1_gw_ip: "{{ hostvars[inventory_hostname]['private_net_gw_ip'] }}"
...